# Generated by Django 3.1.5 on 2021-02-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210205_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('publish', models.BooleanField(default=False)),
                ('our_works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ourworks')),
            ],
        ),
    ]
